<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>formation_planner</name>
  <version>0.0.0</version>
  <description>Formation planning pipeline: shape sampling, coordinate mapping, drone validation, optimal assignment, and MAPF path planning</description>
  <maintainer email="tc20040709@gmail.com">tiffany</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclpy</depend>
  <depend>formation_msgs</depend>
  <depend>geometry_msgs</depend>

  <!-- Not resolvable via rosdep - install manually:
       pip install scipy visvalingamwyatt 
       pip install kneed -->
  <exec_depend>python3-scipy</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
