// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from formation_msgs:msg/GeneratedTransform.idl
// generated code does not contain a copyright notice

#ifndef FORMATION_MSGS__MSG__DETAIL__GENERATED_TRANSFORM__STRUCT_H_
#define FORMATION_MSGS__MSG__DETAIL__GENERATED_TRANSFORM__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'generated_code'
// Member 'plan_description'
#include "rosidl_runtime_c/string.h"
// Member 'current_points'
#include "geometry_msgs/msg/detail/point__struct.h"

/// Struct defined in msg/GeneratedTransform in the package formation_msgs.
/**
  * GeneratedTransform.msg
  * Code generated by the LLM to implement a refinement instruction, plus
  * the point set it should be executed against.
  *
  * Published by : llm_interface_node       (topic: /refinement/generated_transform)
  * Subscribed by: coords_adjust_node
 */
typedef struct formation_msgs__msg__GeneratedTransform
{
  rosidl_runtime_c__String generated_code;
  rosidl_runtime_c__String plan_description;
  geometry_msgs__msg__Point__Sequence current_points;
} formation_msgs__msg__GeneratedTransform;

// Struct for a sequence of formation_msgs__msg__GeneratedTransform.
typedef struct formation_msgs__msg__GeneratedTransform__Sequence
{
  formation_msgs__msg__GeneratedTransform * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} formation_msgs__msg__GeneratedTransform__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // FORMATION_MSGS__MSG__DETAIL__GENERATED_TRANSFORM__STRUCT_H_
